#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Sep 28 15:26:56 2021

@author: ed20b3m
"""

number = [1, 2, 3, 4, 5]

for i in number:
    print(i)

sum = 0
for x in number:
    sum = sum + x
print(sum)
