#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Sep 28 15:07:18 2021

@author: ed20b3m
"""

sentence = input("please input a sentence: ")

letter = input("please input a letter: ")

print("The letter",letter,"occurs",sentence.count(letter),'times in "',sentence,'"')
