#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Oct  7 13:42:11 2021

@author: ed20b3m
"""

# create a variable called a of type list
a = []
for i in range(5):
    # append an empty list to a
    a.append([])
    for j in range(5):
        # append 0 to the ith list of a
        a[i].append(0)
# print out a
print("", end='')

for x in range(0, 4):
    print(a[i], ",\n", sep="")
