#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Oct  7 13:53:20 2021

@author: ed20b3m
"""
nums = []

for a in range(10):
    userInput = int(input("please enter a number: "))
    nums.append(userInput)

sum = 0

for num in nums:
    sum += num

print("sum =", sum)
print("average =", sum/len(nums))
