#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Oct  7 13:48:54 2021

@author: ed20b3m
"""
a = []

for i in range(5):
    a.append([])
    for j in range(5):
        a[i].append(j*5 + i)

print("", end='')

for x in range(0, 4):
    print(a[i], ",\n", sep="")
